// Copyright (c) wzshiming.  Licensed under the MIT License. Binding code generated by https://git.io/c-for-go.
// 

// WARNING: This file has automatically been generated on Thu, 26 Mar 2026 01:49:42 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "hf_xet.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

