// Copyright (c) wzshiming.  Licensed under the MIT License. Binding code generated by https://git.io/c-for-go.
//

// WARNING: This file has automatically been generated on Fri, 27 Mar 2026 12:39:06 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package xet

/*
#include "xet.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// allocXettokeninfoMemory allocates memory for type C.XetTokenInfo in C.
// The caller is responsible for freeing the this memory via C.free.
func allocXettokeninfoMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfXettokeninfoValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfXettokeninfoValue = unsafe.Sizeof([1]C.XetTokenInfo{})

// copyPCharBytes copies the data from Go slice as *C.char.
func copyPCharBytes(slice *sliceHeader) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfCharValue) * slice.Len,
		Cap:  int(sizeOfCharValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.char)(mem0), allocs
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// allocCharMemory allocates memory for type C.char in C.
// The caller is responsible for freeing the this memory via C.free.
func allocCharMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfCharValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfCharValue = unsafe.Sizeof([1]C.char{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *Xettokeninfo) Ref() *C.XetTokenInfo {
	if x == nil {
		return nil
	}
	return x.ref48359c7
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *Xettokeninfo) Free() {
	if x != nil && x.allocs48359c7 != nil {
		x.allocs48359c7.(*cgoAllocMap).Free()
		x.ref48359c7 = nil
	}
}

// NewXettokeninfoRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewXettokeninfoRef(ref unsafe.Pointer) *Xettokeninfo {
	if ref == nil {
		return nil
	}
	obj := new(Xettokeninfo)
	obj.ref48359c7 = (*C.XetTokenInfo)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *Xettokeninfo) PassRef() (*C.XetTokenInfo, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref48359c7 != nil {
		return x.ref48359c7, nil
	}
	mem48359c7 := allocXettokeninfoMemory(1)
	ref48359c7 := (*C.XetTokenInfo)(mem48359c7)
	allocs48359c7 := new(cgoAllocMap)
	allocs48359c7.Add(mem48359c7)

	var ctoken_allocs *cgoAllocMap
	ref48359c7.token, ctoken_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Token)))
	allocs48359c7.Borrow(ctoken_allocs)

	var cexpiry_allocs *cgoAllocMap
	ref48359c7.expiry, cexpiry_allocs = (C.uint64_t)(x.Expiry), cgoAllocsUnknown
	allocs48359c7.Borrow(cexpiry_allocs)

	x.ref48359c7 = ref48359c7
	x.allocs48359c7 = allocs48359c7
	return ref48359c7, allocs48359c7

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x Xettokeninfo) PassValue() (C.XetTokenInfo, *cgoAllocMap) {
	if x.ref48359c7 != nil {
		return *x.ref48359c7, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *Xettokeninfo) Deref() {
	if x.ref48359c7 == nil {
		return
	}
	hxfc4425b := (*sliceHeader)(unsafe.Pointer(&x.Token))
	hxfc4425b.Data = unsafe.Pointer(x.ref48359c7.token)
	hxfc4425b.Cap = 0x7fffffff
	// hxfc4425b.Len = ? x.Token x.ref48359c7.token

	x.Expiry = (uint64)(x.ref48359c7.expiry)
}

// allocXetuploadinfoMemory allocates memory for type C.XetUploadInfo in C.
// The caller is responsible for freeing the this memory via C.free.
func allocXetuploadinfoMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfXetuploadinfoValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfXetuploadinfoValue = unsafe.Sizeof([1]C.XetUploadInfo{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *Xetuploadinfo) Ref() *C.XetUploadInfo {
	if x == nil {
		return nil
	}
	return x.ref1236d3d1
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *Xetuploadinfo) Free() {
	if x != nil && x.allocs1236d3d1 != nil {
		x.allocs1236d3d1.(*cgoAllocMap).Free()
		x.ref1236d3d1 = nil
	}
}

// NewXetuploadinfoRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewXetuploadinfoRef(ref unsafe.Pointer) *Xetuploadinfo {
	if ref == nil {
		return nil
	}
	obj := new(Xetuploadinfo)
	obj.ref1236d3d1 = (*C.XetUploadInfo)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *Xetuploadinfo) PassRef() (*C.XetUploadInfo, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref1236d3d1 != nil {
		return x.ref1236d3d1, nil
	}
	mem1236d3d1 := allocXetuploadinfoMemory(1)
	ref1236d3d1 := (*C.XetUploadInfo)(mem1236d3d1)
	allocs1236d3d1 := new(cgoAllocMap)
	allocs1236d3d1.Add(mem1236d3d1)

	var chash_allocs *cgoAllocMap
	ref1236d3d1.hash, chash_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Hash)))
	allocs1236d3d1.Borrow(chash_allocs)

	var cfile_size_allocs *cgoAllocMap
	ref1236d3d1.file_size, cfile_size_allocs = (C.uint64_t)(x.FileSize), cgoAllocsUnknown
	allocs1236d3d1.Borrow(cfile_size_allocs)

	var csha256_allocs *cgoAllocMap
	ref1236d3d1.sha256, csha256_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Sha256)))
	allocs1236d3d1.Borrow(csha256_allocs)

	x.ref1236d3d1 = ref1236d3d1
	x.allocs1236d3d1 = allocs1236d3d1
	return ref1236d3d1, allocs1236d3d1

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x Xetuploadinfo) PassValue() (C.XetUploadInfo, *cgoAllocMap) {
	if x.ref1236d3d1 != nil {
		return *x.ref1236d3d1, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *Xetuploadinfo) Deref() {
	if x.ref1236d3d1 == nil {
		return
	}
	hxf95e7c8 := (*sliceHeader)(unsafe.Pointer(&x.Hash))
	hxf95e7c8.Data = unsafe.Pointer(x.ref1236d3d1.hash)
	hxf95e7c8.Cap = 0x7fffffff
	// hxf95e7c8.Len = ? x.Hash x.ref1236d3d1.hash

	x.FileSize = (uint64)(x.ref1236d3d1.file_size)
	hxff2234b := (*sliceHeader)(unsafe.Pointer(&x.Sha256))
	hxff2234b.Data = unsafe.Pointer(x.ref1236d3d1.sha256)
	hxff2234b.Cap = 0x7fffffff
	// hxff2234b.Len = ? x.Sha256 x.ref1236d3d1.sha256

}

// allocXetuploadresultMemory allocates memory for type C.XetUploadResult in C.
// The caller is responsible for freeing the this memory via C.free.
func allocXetuploadresultMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfXetuploadresultValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfXetuploadresultValue = unsafe.Sizeof([1]C.XetUploadResult{})

const sizeOfPtr = unsafe.Sizeof(&struct{}{})

// unpackSXetuploadinfo transforms a sliced Go data structure into plain C format.
func unpackSXetuploadinfo(x []Xetuploadinfo) (unpacked *C.XetUploadInfo, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocXetuploadinfoMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.XetUploadInfo)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.XetUploadInfo)(h.Data)
	return
}

// packSXetuploadinfo reads sliced Go data structure out from plain C format.
func packSXetuploadinfo(v []Xetuploadinfo, ptr0 *C.XetUploadInfo) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfXetuploadinfoValue]C.XetUploadInfo)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewXetuploadinfoRef(unsafe.Pointer(&ptr1))
	}
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *Xetuploadresult) Ref() *C.XetUploadResult {
	if x == nil {
		return nil
	}
	return x.ref30b7a435
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *Xetuploadresult) Free() {
	if x != nil && x.allocs30b7a435 != nil {
		x.allocs30b7a435.(*cgoAllocMap).Free()
		x.ref30b7a435 = nil
	}
}

// NewXetuploadresultRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewXetuploadresultRef(ref unsafe.Pointer) *Xetuploadresult {
	if ref == nil {
		return nil
	}
	obj := new(Xetuploadresult)
	obj.ref30b7a435 = (*C.XetUploadResult)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *Xetuploadresult) PassRef() (*C.XetUploadResult, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref30b7a435 != nil {
		return x.ref30b7a435, nil
	}
	mem30b7a435 := allocXetuploadresultMemory(1)
	ref30b7a435 := (*C.XetUploadResult)(mem30b7a435)
	allocs30b7a435 := new(cgoAllocMap)
	allocs30b7a435.Add(mem30b7a435)

	var citems_allocs *cgoAllocMap
	ref30b7a435.items, citems_allocs = unpackSXetuploadinfo(x.Items)
	allocs30b7a435.Borrow(citems_allocs)

	var ccount_allocs *cgoAllocMap
	ref30b7a435.count, ccount_allocs = (C.size_t)(x.Count), cgoAllocsUnknown
	allocs30b7a435.Borrow(ccount_allocs)

	var cerror_allocs *cgoAllocMap
	ref30b7a435.error, cerror_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Error)))
	allocs30b7a435.Borrow(cerror_allocs)

	x.ref30b7a435 = ref30b7a435
	x.allocs30b7a435 = allocs30b7a435
	return ref30b7a435, allocs30b7a435

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x Xetuploadresult) PassValue() (C.XetUploadResult, *cgoAllocMap) {
	if x.ref30b7a435 != nil {
		return *x.ref30b7a435, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *Xetuploadresult) Deref() {
	if x.ref30b7a435 == nil {
		return
	}
	packSXetuploadinfo(x.Items, x.ref30b7a435.items)
	x.Count = (uint64)(x.ref30b7a435.count)
	hxff73280 := (*sliceHeader)(unsafe.Pointer(&x.Error))
	hxff73280.Data = unsafe.Pointer(x.ref30b7a435.error)
	hxff73280.Cap = 0x7fffffff
	// hxff73280.Len = ? x.Error x.ref30b7a435.error

}

// allocXetdownloadinfoMemory allocates memory for type C.XetDownloadInfo in C.
// The caller is responsible for freeing the this memory via C.free.
func allocXetdownloadinfoMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfXetdownloadinfoValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfXetdownloadinfoValue = unsafe.Sizeof([1]C.XetDownloadInfo{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *Xetdownloadinfo) Ref() *C.XetDownloadInfo {
	if x == nil {
		return nil
	}
	return x.ref8bd2335d
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *Xetdownloadinfo) Free() {
	if x != nil && x.allocs8bd2335d != nil {
		x.allocs8bd2335d.(*cgoAllocMap).Free()
		x.ref8bd2335d = nil
	}
}

// NewXetdownloadinfoRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewXetdownloadinfoRef(ref unsafe.Pointer) *Xetdownloadinfo {
	if ref == nil {
		return nil
	}
	obj := new(Xetdownloadinfo)
	obj.ref8bd2335d = (*C.XetDownloadInfo)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *Xetdownloadinfo) PassRef() (*C.XetDownloadInfo, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref8bd2335d != nil {
		return x.ref8bd2335d, nil
	}
	mem8bd2335d := allocXetdownloadinfoMemory(1)
	ref8bd2335d := (*C.XetDownloadInfo)(mem8bd2335d)
	allocs8bd2335d := new(cgoAllocMap)
	allocs8bd2335d.Add(mem8bd2335d)

	var cdestination_path_allocs *cgoAllocMap
	ref8bd2335d.destination_path, cdestination_path_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.DestinationPath)))
	allocs8bd2335d.Borrow(cdestination_path_allocs)

	var chash_allocs *cgoAllocMap
	ref8bd2335d.hash, chash_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Hash)))
	allocs8bd2335d.Borrow(chash_allocs)

	var cfile_size_allocs *cgoAllocMap
	ref8bd2335d.file_size, cfile_size_allocs = (C.int64_t)(x.FileSize), cgoAllocsUnknown
	allocs8bd2335d.Borrow(cfile_size_allocs)

	x.ref8bd2335d = ref8bd2335d
	x.allocs8bd2335d = allocs8bd2335d
	return ref8bd2335d, allocs8bd2335d

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x Xetdownloadinfo) PassValue() (C.XetDownloadInfo, *cgoAllocMap) {
	if x.ref8bd2335d != nil {
		return *x.ref8bd2335d, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *Xetdownloadinfo) Deref() {
	if x.ref8bd2335d == nil {
		return
	}
	hxfa9955c := (*sliceHeader)(unsafe.Pointer(&x.DestinationPath))
	hxfa9955c.Data = unsafe.Pointer(x.ref8bd2335d.destination_path)
	hxfa9955c.Cap = 0x7fffffff
	// hxfa9955c.Len = ? x.DestinationPath x.ref8bd2335d.destination_path

	hxfa3f05c := (*sliceHeader)(unsafe.Pointer(&x.Hash))
	hxfa3f05c.Data = unsafe.Pointer(x.ref8bd2335d.hash)
	hxfa3f05c.Cap = 0x7fffffff
	// hxfa3f05c.Len = ? x.Hash x.ref8bd2335d.hash

	x.FileSize = (int64)(x.ref8bd2335d.file_size)
}

// allocXetdownloadresultMemory allocates memory for type C.XetDownloadResult in C.
// The caller is responsible for freeing the this memory via C.free.
func allocXetdownloadresultMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfXetdownloadresultValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfXetdownloadresultValue = unsafe.Sizeof([1]C.XetDownloadResult{})

// allocPCharMemory allocates memory for type *C.char in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPCharMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPCharValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPCharValue = unsafe.Sizeof([1]*C.char{})

// unpackSSByte transforms a sliced Go data structure into plain C format.
func unpackSSByte(x [][]byte) (unpacked **C.char, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocPCharMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]*C.char)(unsafe.Pointer(h0))
	for i0 := range x {
		h := (*sliceHeader)(unsafe.Pointer(&x[i0]))
		v0[i0] = (*C.char)(h.Data)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (**C.char)(h.Data)
	return
}

// packSSByte reads sliced Go data structure out from plain C format.
func packSSByte(v [][]byte, ptr0 **C.char) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfPtr]*C.char)(unsafe.Pointer(ptr0)))[i0]
		hxf0d18b7 := (*sliceHeader)(unsafe.Pointer(&v[i0]))
		hxf0d18b7.Data = unsafe.Pointer(ptr1)
		hxf0d18b7.Cap = 0x7fffffff
		// hxf0d18b7.Len = ?
	}
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *Xetdownloadresult) Ref() *C.XetDownloadResult {
	if x == nil {
		return nil
	}
	return x.ref78b08ee
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *Xetdownloadresult) Free() {
	if x != nil && x.allocs78b08ee != nil {
		x.allocs78b08ee.(*cgoAllocMap).Free()
		x.ref78b08ee = nil
	}
}

// NewXetdownloadresultRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewXetdownloadresultRef(ref unsafe.Pointer) *Xetdownloadresult {
	if ref == nil {
		return nil
	}
	obj := new(Xetdownloadresult)
	obj.ref78b08ee = (*C.XetDownloadResult)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *Xetdownloadresult) PassRef() (*C.XetDownloadResult, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref78b08ee != nil {
		return x.ref78b08ee, nil
	}
	mem78b08ee := allocXetdownloadresultMemory(1)
	ref78b08ee := (*C.XetDownloadResult)(mem78b08ee)
	allocs78b08ee := new(cgoAllocMap)
	allocs78b08ee.Add(mem78b08ee)

	var cpaths_allocs *cgoAllocMap
	ref78b08ee.paths, cpaths_allocs = unpackSSByte(x.Paths)
	allocs78b08ee.Borrow(cpaths_allocs)

	var ccount_allocs *cgoAllocMap
	ref78b08ee.count, ccount_allocs = (C.size_t)(x.Count), cgoAllocsUnknown
	allocs78b08ee.Borrow(ccount_allocs)

	var cerror_allocs *cgoAllocMap
	ref78b08ee.error, cerror_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Error)))
	allocs78b08ee.Borrow(cerror_allocs)

	x.ref78b08ee = ref78b08ee
	x.allocs78b08ee = allocs78b08ee
	return ref78b08ee, allocs78b08ee

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x Xetdownloadresult) PassValue() (C.XetDownloadResult, *cgoAllocMap) {
	if x.ref78b08ee != nil {
		return *x.ref78b08ee, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *Xetdownloadresult) Deref() {
	if x.ref78b08ee == nil {
		return
	}
	packSSByte(x.Paths, x.ref78b08ee.paths)
	x.Count = (uint64)(x.ref78b08ee.count)
	hxf2fab0d := (*sliceHeader)(unsafe.Pointer(&x.Error))
	hxf2fab0d.Data = unsafe.Pointer(x.ref78b08ee.error)
	hxf2fab0d.Cap = 0x7fffffff
	// hxf2fab0d.Len = ? x.Error x.ref78b08ee.error

}

// allocXetchunkinfoMemory allocates memory for type C.XetChunkInfo in C.
// The caller is responsible for freeing the this memory via C.free.
func allocXetchunkinfoMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfXetchunkinfoValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfXetchunkinfoValue = unsafe.Sizeof([1]C.XetChunkInfo{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *Xetchunkinfo) Ref() *C.XetChunkInfo {
	if x == nil {
		return nil
	}
	return x.ref5321e746
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *Xetchunkinfo) Free() {
	if x != nil && x.allocs5321e746 != nil {
		x.allocs5321e746.(*cgoAllocMap).Free()
		x.ref5321e746 = nil
	}
}

// NewXetchunkinfoRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewXetchunkinfoRef(ref unsafe.Pointer) *Xetchunkinfo {
	if ref == nil {
		return nil
	}
	obj := new(Xetchunkinfo)
	obj.ref5321e746 = (*C.XetChunkInfo)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *Xetchunkinfo) PassRef() (*C.XetChunkInfo, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref5321e746 != nil {
		return x.ref5321e746, nil
	}
	mem5321e746 := allocXetchunkinfoMemory(1)
	ref5321e746 := (*C.XetChunkInfo)(mem5321e746)
	allocs5321e746 := new(cgoAllocMap)
	allocs5321e746.Add(mem5321e746)

	var chash_allocs *cgoAllocMap
	ref5321e746.hash, chash_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Hash)))
	allocs5321e746.Borrow(chash_allocs)

	var csize_allocs *cgoAllocMap
	ref5321e746.size, csize_allocs = (C.uint64_t)(x.Size), cgoAllocsUnknown
	allocs5321e746.Borrow(csize_allocs)

	x.ref5321e746 = ref5321e746
	x.allocs5321e746 = allocs5321e746
	return ref5321e746, allocs5321e746

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x Xetchunkinfo) PassValue() (C.XetChunkInfo, *cgoAllocMap) {
	if x.ref5321e746 != nil {
		return *x.ref5321e746, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *Xetchunkinfo) Deref() {
	if x.ref5321e746 == nil {
		return
	}
	hxf69fe70 := (*sliceHeader)(unsafe.Pointer(&x.Hash))
	hxf69fe70.Data = unsafe.Pointer(x.ref5321e746.hash)
	hxf69fe70.Cap = 0x7fffffff
	// hxf69fe70.Len = ? x.Hash x.ref5321e746.hash

	x.Size = (uint64)(x.ref5321e746.size)
}

// allocXetchunkresultMemory allocates memory for type C.XetChunkResult in C.
// The caller is responsible for freeing the this memory via C.free.
func allocXetchunkresultMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfXetchunkresultValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfXetchunkresultValue = unsafe.Sizeof([1]C.XetChunkResult{})

// unpackSXetchunkinfo transforms a sliced Go data structure into plain C format.
func unpackSXetchunkinfo(x []Xetchunkinfo) (unpacked *C.XetChunkInfo, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocXetchunkinfoMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.XetChunkInfo)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.XetChunkInfo)(h.Data)
	return
}

// packSXetchunkinfo reads sliced Go data structure out from plain C format.
func packSXetchunkinfo(v []Xetchunkinfo, ptr0 *C.XetChunkInfo) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfXetchunkinfoValue]C.XetChunkInfo)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewXetchunkinfoRef(unsafe.Pointer(&ptr1))
	}
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *Xetchunkresult) Ref() *C.XetChunkResult {
	if x == nil {
		return nil
	}
	return x.ref2f030d4a
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *Xetchunkresult) Free() {
	if x != nil && x.allocs2f030d4a != nil {
		x.allocs2f030d4a.(*cgoAllocMap).Free()
		x.ref2f030d4a = nil
	}
}

// NewXetchunkresultRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewXetchunkresultRef(ref unsafe.Pointer) *Xetchunkresult {
	if ref == nil {
		return nil
	}
	obj := new(Xetchunkresult)
	obj.ref2f030d4a = (*C.XetChunkResult)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *Xetchunkresult) PassRef() (*C.XetChunkResult, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref2f030d4a != nil {
		return x.ref2f030d4a, nil
	}
	mem2f030d4a := allocXetchunkresultMemory(1)
	ref2f030d4a := (*C.XetChunkResult)(mem2f030d4a)
	allocs2f030d4a := new(cgoAllocMap)
	allocs2f030d4a.Add(mem2f030d4a)

	var citems_allocs *cgoAllocMap
	ref2f030d4a.items, citems_allocs = unpackSXetchunkinfo(x.Items)
	allocs2f030d4a.Borrow(citems_allocs)

	var ccount_allocs *cgoAllocMap
	ref2f030d4a.count, ccount_allocs = (C.size_t)(x.Count), cgoAllocsUnknown
	allocs2f030d4a.Borrow(ccount_allocs)

	var cerror_allocs *cgoAllocMap
	ref2f030d4a.error, cerror_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Error)))
	allocs2f030d4a.Borrow(cerror_allocs)

	x.ref2f030d4a = ref2f030d4a
	x.allocs2f030d4a = allocs2f030d4a
	return ref2f030d4a, allocs2f030d4a

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x Xetchunkresult) PassValue() (C.XetChunkResult, *cgoAllocMap) {
	if x.ref2f030d4a != nil {
		return *x.ref2f030d4a, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *Xetchunkresult) Deref() {
	if x.ref2f030d4a == nil {
		return
	}
	packSXetchunkinfo(x.Items, x.ref2f030d4a.items)
	x.Count = (uint64)(x.ref2f030d4a.count)
	hxf65bf54 := (*sliceHeader)(unsafe.Pointer(&x.Error))
	hxf65bf54.Data = unsafe.Pointer(x.ref2f030d4a.error)
	hxf65bf54.Cap = 0x7fffffff
	// hxf65bf54.Len = ? x.Error x.ref2f030d4a.error

}

// unpackArgSString transforms a sliced Go data structure into plain C format.
func unpackArgSString(x []string) (unpacked **C.char, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocPCharMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]*C.char)(unsafe.Pointer(h0))
	for i0 := range x {
		v0[i0], _ = unpackPCharString(x[i0])
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (**C.char)(h.Data)
	return
}

// unpackPCharString copies the data from Go string as *C.char.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}

// packSString reads sliced Go data structure out from plain C format.
func packSString(v []string, ptr0 **C.char) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfPtr]*C.char)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = packPCharString(ptr1)
	}
}

// packPCharString creates a Go string backed by *C.char and avoids copying.
func packPCharString(p *C.char) (raw string) {
	if p != nil && *p != 0 {
		h := (*stringHeader)(unsafe.Pointer(&raw))
		h.Data = unsafe.Pointer(p)
		for *p != 0 {
			p = (*C.char)(unsafe.Pointer(uintptr(unsafe.Pointer(p)) + 1)) // p++
		}
		h.Len = int(uintptr(unsafe.Pointer(p)) - uintptr(h.Data))
	}
	return
}

// RawString reperesents a string backed by data on the C side.
type RawString string

// Copy returns a Go-managed copy of raw string.
func (raw RawString) Copy() string {
	if len(raw) == 0 {
		return ""
	}
	h := (*stringHeader)(unsafe.Pointer(&raw))
	return C.GoStringN((*C.char)(h.Data), C.int(h.Len))
}

// copyPUint8Bytes copies the data from Go slice as *C.uint8_t.
func copyPUint8Bytes(slice *sliceHeader) (*C.uint8_t, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfUint8Value) * slice.Len,
		Cap:  int(sizeOfUint8Value) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.uint8_t)(mem0), allocs
}

// allocUint8Memory allocates memory for type C.uint8_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocUint8Memory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfUint8Value))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfUint8Value = unsafe.Sizeof([1]C.uint8_t{})

// unpackArgSXetchunkinfo transforms a sliced Go data structure into plain C format.
func unpackArgSXetchunkinfo(x []Xetchunkinfo) (unpacked *C.XetChunkInfo, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocXetchunkinfoMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.XetChunkInfo)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.XetChunkInfo)(h.Data)
	return
}

// unpackArgSXetdownloadinfo transforms a sliced Go data structure into plain C format.
func unpackArgSXetdownloadinfo(x []Xetdownloadinfo) (unpacked *C.XetDownloadInfo, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocXetdownloadinfoMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.XetDownloadInfo)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.XetDownloadInfo)(h.Data)
	return
}

// packSXetdownloadinfo reads sliced Go data structure out from plain C format.
func packSXetdownloadinfo(v []Xetdownloadinfo, ptr0 *C.XetDownloadInfo) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfXetdownloadinfoValue]C.XetDownloadInfo)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewXetdownloadinfoRef(unsafe.Pointer(&ptr1))
	}
}
