// Copyright (c) wzshiming.  Licensed under the MIT License. Binding code generated by https://git.io/c-for-go.
//

// WARNING: This file has automatically been generated on Fri, 27 Mar 2026 12:39:06 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package xet

/*
#include "xet.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
// H as defined in xet/xet.h:15

)
