// Copyright (c) wzshiming.  Licensed under the MIT License. Binding code generated by https://git.io/c-for-go.
//

// WARNING: This file has automatically been generated on Fri, 27 Mar 2026 12:39:06 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package xet provides Go CGo bindings for the xet-core HuggingFace Xet storage library.  The low-level API mirrors the C interface defined in xet.h; for a more idiomatic Go experience use the high-level wrappers in the parent package.
*/
package xet
