// Copyright (c) wzshiming.  Licensed under the MIT License. Binding code generated by https://git.io/c-for-go.
//

// WARNING: This file has automatically been generated on Fri, 27 Mar 2026 12:39:06 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package xet

/*
#include "xet.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Xettokeninfo as declared in xet/xet.h:34
type Xettokeninfo struct {
	Token         []byte
	Expiry        uint64
	ref48359c7    *C.XetTokenInfo
	allocs48359c7 interface{}
}

// Xetuploadinfo as declared in xet/xet.h:42
type Xetuploadinfo struct {
	Hash           []byte
	FileSize       uint64
	Sha256         []byte
	ref1236d3d1    *C.XetUploadInfo
	allocs1236d3d1 interface{}
}

// Xetuploadresult as declared in xet/xet.h:55
type Xetuploadresult struct {
	Items          []Xetuploadinfo
	Count          uint64
	Error          []byte
	ref30b7a435    *C.XetUploadResult
	allocs30b7a435 interface{}
}

// Xetdownloadinfo as declared in xet/xet.h:63
type Xetdownloadinfo struct {
	DestinationPath []byte
	Hash            []byte
	FileSize        int64
	ref8bd2335d     *C.XetDownloadInfo
	allocs8bd2335d  interface{}
}

// Xetdownloadresult as declared in xet/xet.h:76
type Xetdownloadresult struct {
	Paths         [][]byte
	Count         uint64
	Error         []byte
	ref78b08ee    *C.XetDownloadResult
	allocs78b08ee interface{}
}

// Xetchunkinfo as declared in xet/xet.h:132
type Xetchunkinfo struct {
	Hash           []byte
	Size           uint64
	ref5321e746    *C.XetChunkInfo
	allocs5321e746 interface{}
}

// Xetchunkresult as declared in xet/xet.h:145
type Xetchunkresult struct {
	Items          []Xetchunkinfo
	Count          uint64
	Error          []byte
	ref2f030d4a    *C.XetChunkResult
	allocs2f030d4a interface{}
}
