/* xet.h — C API for the xet-core HuggingFace Xet storage library.
 *
 * This header defines the C-compatible interface generated by xet-core's
 * Rust implementation for use by non-Python language bindings (e.g. Go).
 *
 * Memory management
 * -----------------
 * All result structs returned by xet_* functions are heap-allocated.
 * The caller MUST release them with the corresponding xet_free_* functions.
 * String fields within result structs are owned by the struct; do not free
 * them individually.
 */

#ifndef xet_H
#define xet_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------------------------
 * Common types
 * ---------------------------------------------------------------------- */

/** Authentication token paired with its UNIX-epoch expiry time (seconds). */
typedef struct XetTokenInfo {
    const char *token;  /**< Bearer token string (NUL-terminated). */
    uint64_t    expiry; /**< Token expiry as UNIX epoch seconds (0 = no expiry). */
} XetTokenInfo;

/** Metadata returned for each successfully uploaded or hashed file. */
typedef struct XetUploadInfo {
    const char *hash;      /**< Xet content-hash (hex string, NUL-terminated). */
    uint64_t    file_size; /**< File size in bytes. */
    const char *sha256;    /**< SHA-256 hex digest, or NULL if not computed. */
} XetUploadInfo;

/**
 * A batch upload / hash result.
 *
 * On success  : error == NULL, items points to an array of @p count elements.
 * On failure  : error != NULL, items may be NULL.
 */
typedef struct XetUploadResult {
    XetUploadInfo *items; /**< Array of per-file upload metadata (may be NULL on error). */
    size_t         count; /**< Number of elements in @p items. */
    const char    *error; /**< Human-readable error string, or NULL on success. */
} XetUploadResult;

/** Input descriptor for a single file to download. */
typedef struct XetDownloadInfo {
    const char *destination_path; /**< Local filesystem path for the downloaded file. */
    const char *hash;             /**< Xet content-hash to fetch (hex string). */
    int64_t     file_size;        /**< Expected size in bytes, or -1 if unknown. */
} XetDownloadInfo;

/**
 * A batch download result.
 *
 * On success  : error == NULL, paths points to an array of @p count C strings.
 * On failure  : error != NULL, paths may be NULL.
 */
typedef struct XetDownloadResult {
    char       **paths; /**< Array of destination paths for downloaded files. */
    size_t       count; /**< Number of elements in @p paths. */
    const char  *error; /**< Human-readable error string, or NULL on success. */
} XetDownloadResult;

/* -------------------------------------------------------------------------
 * Upload functions
 * ---------------------------------------------------------------------- */

/**
 * Upload files specified by path to HuggingFace Xet storage.
 *
 * @param file_paths   NULL-terminated array of NUL-terminated UTF-8 file paths.
 * @param file_count   Number of entries in @p file_paths.
 * @param endpoint     CAS endpoint URL (NUL-terminated), or NULL for default.
 * @param token_info   Authentication token, or NULL for unauthenticated access.
 * @param sha256s      Optional pre-computed SHA-256 hex digests; one per file,
 *                     or NULL to compute them automatically.
 * @param sha256_count Number of entries in @p sha256s (must equal @p file_count
 *                     when @p sha256s is non-NULL, and 0 when @p sha256s is NULL).
 * @param skip_sha256  Non-zero to skip SHA-256 verification entirely.
 *                     Mutually exclusive with non-NULL @p sha256s.
 * @return Heap-allocated XetUploadResult; caller must free with xet_free_upload_result().
 */
XetUploadResult *xet_upload_files(
    const char    **file_paths,
    size_t          file_count,
    const char     *endpoint,
    XetTokenInfo   *token_info,
    const char    **sha256s,
    size_t          sha256_count,
    int             skip_sha256
);

/* -------------------------------------------------------------------------
 * Hash function
 * ---------------------------------------------------------------------- */

/**
 * Compute Xet content-hashes for local files without uploading.
 *
 * Useful for pre-flight verification or deduplication checks.
 *
 * @param file_paths  NULL-terminated array of NUL-terminated UTF-8 file paths.
 * @param file_count  Number of entries in @p file_paths.
 * @return Heap-allocated XetUploadResult; caller must free with xet_free_upload_result().
 */
XetUploadResult *xet_hash_files(
    const char **file_paths,
    size_t       file_count
);

/* -------------------------------------------------------------------------
 * Download function
 * ---------------------------------------------------------------------- */

/**
 * Download files from HuggingFace Xet storage to the local filesystem.
 *
 * @param files       Array of XetDownloadInfo descriptors.
 * @param file_count  Number of entries in @p files.
 * @param endpoint    CAS endpoint URL (NUL-terminated), or NULL for default.
 * @param token_info  Authentication token, or NULL for unauthenticated access.
 * @return Heap-allocated XetDownloadResult; caller must free with xet_free_download_result().
 */
XetDownloadResult *xet_download_files(
    XetDownloadInfo *files,
    size_t           file_count,
    const char      *endpoint,
    XetTokenInfo    *token_info
);

/* -------------------------------------------------------------------------
 * Memory management (upload / download)
 * ---------------------------------------------------------------------- */

/**
 * Release a XetUploadResult previously returned by xet_upload_files(),
 * xet_upload_bytes(), or xet_hash_files().
 *
 * Passing NULL is a no-op.
 */
void xet_free_upload_result(XetUploadResult *result);

/**
 * Release a XetDownloadResult previously returned by xet_download_files().
 *
 * Passing NULL is a no-op.
 */
void xet_free_download_result(XetDownloadResult *result);

/* -------------------------------------------------------------------------
 * Chunking types and functions
 * ---------------------------------------------------------------------- */

/** Metadata for a single content-defined chunk. */
typedef struct XetChunkInfo {
    const char *hash; /**< Chunk hash (hex string, NUL-terminated). */
    uint64_t    size; /**< Chunk size in bytes. */
} XetChunkInfo;

/**
 * Result of a chunking operation.
 *
 * On success  : error == NULL, items points to an array of @p count elements.
 * On failure  : error != NULL, items may be NULL.
 */
typedef struct XetChunkResult {
    XetChunkInfo *items; /**< Array of per-chunk metadata (may be NULL on error). */
    size_t        count; /**< Number of elements in @p items. */
    const char   *error; /**< Human-readable error string, or NULL on success. */
} XetChunkResult;

/**
 * Split a raw byte buffer into content-defined chunks.
 *
 * @param data     Pointer to the input bytes.
 * @param data_len Number of bytes in @p data.
 * @return Heap-allocated XetChunkResult; caller must free with xet_free_chunk_result().
 */
XetChunkResult *xet_chunk_data(const uint8_t *data, size_t data_len);

/**
 * Split a file on disk into content-defined chunks.
 *
 * @param file_path NUL-terminated UTF-8 path to the input file.
 * @return Heap-allocated XetChunkResult; caller must free with xet_free_chunk_result().
 */
XetChunkResult *xet_chunk_file(const char *file_path);

/**
 * Release a XetChunkResult previously returned by xet_chunk_data() or
 * xet_chunk_file().
 *
 * Passing NULL is a no-op.
 */
void xet_free_chunk_result(XetChunkResult *result);

/* -------------------------------------------------------------------------
 * Hash types and functions
 * ---------------------------------------------------------------------- */

/**
 * Result of a single hash computation.
 *
 * On success  : error == NULL, hash is a NUL-terminated hex string.
 * On failure  : error != NULL, hash may be NULL.
 */
typedef struct XetHashResult {
    const char *hash;  /**< Hex hash string (NUL-terminated), or NULL on error. */
    const char *error; /**< Human-readable error string, or NULL on success. */
} XetHashResult;

/**
 * Compute the Xet chunk hash of raw bytes.
 *
 * @param data     Pointer to the input bytes.
 * @param data_len Number of bytes in @p data.
 * @return Heap-allocated XetHashResult; caller must free with xet_free_hash_result().
 */
XetHashResult *xet_compute_chunk_hash(const uint8_t *data, size_t data_len);

/**
 * Compute the xorb hash from an ordered list of chunk hashes and sizes.
 *
 * @param chunk_hashes Array of NUL-terminated hex chunk hash strings.
 * @param chunk_sizes  Array of chunk sizes in bytes (parallel to @p chunk_hashes).
 * @param count        Number of elements in both arrays.
 * @return Heap-allocated XetHashResult; caller must free with xet_free_hash_result().
 */
XetHashResult *xet_compute_xorb_hash(
    const char    **chunk_hashes,
    const uint64_t *chunk_sizes,
    size_t          count
);

/**
 * Compute the file hash from an ordered list of chunk hashes and sizes.
 *
 * @param chunk_hashes Array of NUL-terminated hex chunk hash strings.
 * @param chunk_sizes  Array of chunk sizes in bytes (parallel to @p chunk_hashes).
 * @param count        Number of elements in both arrays.
 * @return Heap-allocated XetHashResult; caller must free with xet_free_hash_result().
 */
XetHashResult *xet_compute_file_hash(
    const char    **chunk_hashes,
    const uint64_t *chunk_sizes,
    size_t          count
);

/**
 * Compute the range hash from an ordered list of chunk hashes.
 *
 * @param chunk_hashes Array of NUL-terminated hex chunk hash strings.
 * @param count        Number of elements in @p chunk_hashes.
 * @return Heap-allocated XetHashResult; caller must free with xet_free_hash_result().
 */
XetHashResult *xet_compute_range_hash(
    const char **chunk_hashes,
    size_t       count
);

/**
 * Release a XetHashResult previously returned by any xet_compute_*_hash() function.
 *
 * Passing NULL is a no-op.
 */
void xet_free_hash_result(XetHashResult *result);

/* -------------------------------------------------------------------------
 * Xorb-check types and functions
 * ---------------------------------------------------------------------- */

/**
 * Result of an xorb integrity check.
 *
 * On success  : error == NULL, xorb_hash is the computed hash.
 * On failure  : error != NULL, other fields may be zero/NULL.
 */
typedef struct XetXorbCheckResult {
    const char   *xorb_hash;   /**< Computed xorb hash (hex, NUL-terminated). */
    XetChunkInfo *chunks;      /**< Array of per-chunk metadata. */
    size_t        chunk_count; /**< Number of elements in @p chunks. */
    uint64_t      total_bytes; /**< Total data bytes across all chunks. */
    const char   *error;       /**< Human-readable error string, or NULL on success. */
} XetXorbCheckResult;

/**
 * Deserialize an xorb object from a raw byte buffer and compute its hash.
 *
 * @param data     Pointer to the input bytes.
 * @param data_len Number of bytes in @p data.
 * @return Heap-allocated XetXorbCheckResult; caller must free with xet_free_xorb_check_result().
 */
XetXorbCheckResult *xet_check_xorb_data(const uint8_t *data, size_t data_len);

/**
 * Deserialize an xorb object from a file and compute its hash.
 *
 * @param file_path NUL-terminated UTF-8 path to the xorb file.
 * @return Heap-allocated XetXorbCheckResult; caller must free with xet_free_xorb_check_result().
 */
XetXorbCheckResult *xet_check_xorb_file(const char *file_path);

/**
 * Release a XetXorbCheckResult previously returned by xet_check_xorb_data()
 * or xet_check_xorb_file().
 *
 * Passing NULL is a no-op.
 */
void xet_free_xorb_check_result(XetXorbCheckResult *result);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* xet_H */
