// Copyright (c) wzshiming.  Licensed under the MIT License. Binding code generated by https://git.io/c-for-go.
//

// WARNING: This file has automatically been generated on Fri, 27 Mar 2026 12:39:06 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package xet

/*
#include "xet.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// UploadFiles function as declared in xet/xet.h:97
func UploadFiles(filePaths []string, fileCount uint64, endpoint string, tokenInfo *Xettokeninfo, sha256s []string, sha256Count uint64, skipSha256 int32) *Xetuploadresult {
	cfilePaths, cfilePathsAllocMap := unpackArgSString(filePaths)
	cfileCount, cfileCountAllocMap := (C.size_t)(fileCount), cgoAllocsUnknown
	cendpoint, cendpointAllocMap := unpackPCharString(endpoint)
	ctokenInfo, ctokenInfoAllocMap := tokenInfo.PassRef()
	csha256s, csha256sAllocMap := unpackArgSString(sha256s)
	csha256Count, csha256CountAllocMap := (C.size_t)(sha256Count), cgoAllocsUnknown
	cskipSha256, cskipSha256AllocMap := (C.int)(skipSha256), cgoAllocsUnknown
	__ret := C.xet_upload_files(cfilePaths, cfileCount, cendpoint, ctokenInfo, csha256s, csha256Count, cskipSha256)
	runtime.KeepAlive(cskipSha256AllocMap)
	runtime.KeepAlive(csha256CountAllocMap)
	packSString(sha256s, csha256s)
	runtime.KeepAlive(csha256sAllocMap)
	runtime.KeepAlive(ctokenInfoAllocMap)
	runtime.KeepAlive(cendpointAllocMap)
	runtime.KeepAlive(cfileCountAllocMap)
	packSString(filePaths, cfilePaths)
	runtime.KeepAlive(cfilePathsAllocMap)
	__v := NewXetuploadresultRef(unsafe.Pointer(__ret))
	return __v
}

// HashFiles function as declared in xet/xet.h:119
func HashFiles(filePaths []string, fileCount uint64) *Xetuploadresult {
	cfilePaths, cfilePathsAllocMap := unpackArgSString(filePaths)
	cfileCount, cfileCountAllocMap := (C.size_t)(fileCount), cgoAllocsUnknown
	__ret := C.xet_hash_files(cfilePaths, cfileCount)
	runtime.KeepAlive(cfileCountAllocMap)
	packSString(filePaths, cfilePaths)
	runtime.KeepAlive(cfilePathsAllocMap)
	__v := NewXetuploadresultRef(unsafe.Pointer(__ret))
	return __v
}

// ChunkData function as declared in xet/xet.h:157
func ChunkData(data []byte, dataLen uint64) *Xetchunkresult {
	cdata, cdataAllocMap := (*C.uint8_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	cdataLen, cdataLenAllocMap := (C.size_t)(dataLen), cgoAllocsUnknown
	__ret := C.xet_chunk_data(cdata, cdataLen)
	runtime.KeepAlive(cdataLenAllocMap)
	runtime.KeepAlive(cdataAllocMap)
	__v := NewXetchunkresultRef(unsafe.Pointer(__ret))
	return __v
}

// HashChunk function as declared in xet/xet.h:169
func HashChunk(data []byte, dataLen uint64) *byte {
	cdata, cdataAllocMap := (*C.uint8_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	cdataLen, cdataLenAllocMap := (C.size_t)(dataLen), cgoAllocsUnknown
	__ret := C.xet_hash_chunk(cdata, cdataLen)
	runtime.KeepAlive(cdataLenAllocMap)
	runtime.KeepAlive(cdataAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// ComputeXorbHash function as declared in xet/xet.h:184
func ComputeXorbHash(chunks []Xetchunkinfo, chunkCount uint64) *byte {
	cchunks, cchunksAllocMap := unpackArgSXetchunkinfo(chunks)
	cchunkCount, cchunkCountAllocMap := (C.size_t)(chunkCount), cgoAllocsUnknown
	__ret := C.xet_compute_xorb_hash(cchunks, cchunkCount)
	runtime.KeepAlive(cchunkCountAllocMap)
	packSXetchunkinfo(chunks, cchunks)
	runtime.KeepAlive(cchunksAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// DownloadFiles function as declared in xet/xet.h:201
func DownloadFiles(files []Xetdownloadinfo, fileCount uint64, endpoint string, tokenInfo *Xettokeninfo) *Xetdownloadresult {
	cfiles, cfilesAllocMap := unpackArgSXetdownloadinfo(files)
	cfileCount, cfileCountAllocMap := (C.size_t)(fileCount), cgoAllocsUnknown
	cendpoint, cendpointAllocMap := unpackPCharString(endpoint)
	ctokenInfo, ctokenInfoAllocMap := tokenInfo.PassRef()
	__ret := C.xet_download_files(cfiles, cfileCount, cendpoint, ctokenInfo)
	runtime.KeepAlive(ctokenInfoAllocMap)
	runtime.KeepAlive(cendpointAllocMap)
	runtime.KeepAlive(cfileCountAllocMap)
	packSXetdownloadinfo(files, cfiles)
	runtime.KeepAlive(cfilesAllocMap)
	__v := NewXetdownloadresultRef(unsafe.Pointer(__ret))
	return __v
}

// FreeUploadResult function as declared in xet/xet.h:217
func FreeUploadResult(result *Xetuploadresult) {
	cresult, cresultAllocMap := result.PassRef()
	C.xet_free_upload_result(cresult)
	runtime.KeepAlive(cresultAllocMap)
}

// FreeDownloadResult function as declared in xet/xet.h:224
func FreeDownloadResult(result *Xetdownloadresult) {
	cresult, cresultAllocMap := result.PassRef()
	C.xet_free_download_result(cresult)
	runtime.KeepAlive(cresultAllocMap)
}

// FreeChunkResult function as declared in xet/xet.h:231
func FreeChunkResult(result *Xetchunkresult) {
	cresult, cresultAllocMap := result.PassRef()
	C.xet_free_chunk_result(cresult)
	runtime.KeepAlive(cresultAllocMap)
}

// FreeString function as declared in xet/xet.h:238
func FreeString(str *byte) {
	cstr, cstrAllocMap := (*C.char)(unsafe.Pointer(str)), cgoAllocsUnknown
	C.xet_free_string(cstr)
	runtime.KeepAlive(cstrAllocMap)
}
