// Copyright (c) wzshiming.  Licensed under the MIT License. Binding code generated by https://git.io/c-for-go.
//

// WARNING: This file has automatically been generated on Thu, 26 Mar 2026 11:25:20 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package xet

/*
#include "xet.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// UploadFiles function as declared in xet/xet.h:91
func UploadFiles(filePaths []string, fileCount uint64, endpoint string, tokenInfo *Xettokeninfo, sha256s []string, sha256Count uint64, skipSha256 int32) *Xetuploadresult {
	cfilePaths, cfilePathsAllocMap := unpackArgSString(filePaths)
	cfileCount, cfileCountAllocMap := (C.size_t)(fileCount), cgoAllocsUnknown
	endpoint = safeString(endpoint)
	cendpoint, cendpointAllocMap := unpackPCharString(endpoint)
	ctokenInfo, ctokenInfoAllocMap := tokenInfo.PassRef()
	csha256s, csha256sAllocMap := unpackArgSString(sha256s)
	csha256Count, csha256CountAllocMap := (C.size_t)(sha256Count), cgoAllocsUnknown
	cskipSha256, cskipSha256AllocMap := (C.int)(skipSha256), cgoAllocsUnknown
	__ret := C.xet_upload_files(cfilePaths, cfileCount, cendpoint, ctokenInfo, csha256s, csha256Count, cskipSha256)
	runtime.KeepAlive(cskipSha256AllocMap)
	runtime.KeepAlive(csha256CountAllocMap)
	packSString(sha256s, csha256s)
	runtime.KeepAlive(csha256sAllocMap)
	runtime.KeepAlive(ctokenInfoAllocMap)
	runtime.KeepAlive(endpoint)
	runtime.KeepAlive(cendpointAllocMap)
	runtime.KeepAlive(cfileCountAllocMap)
	packSString(filePaths, cfilePaths)
	runtime.KeepAlive(cfilePathsAllocMap)
	__v := NewXetuploadresultRef(unsafe.Pointer(__ret))
	return __v
}

// HashFiles function as declared in xet/xet.h:114
func HashFiles(filePaths []string, fileCount uint64) *Xetuploadresult {
	cfilePaths, cfilePathsAllocMap := unpackArgSString(filePaths)
	cfileCount, cfileCountAllocMap := (C.size_t)(fileCount), cgoAllocsUnknown
	__ret := C.xet_hash_files(cfilePaths, cfileCount)
	runtime.KeepAlive(cfileCountAllocMap)
	packSString(filePaths, cfilePaths)
	runtime.KeepAlive(cfilePathsAllocMap)
	__v := NewXetuploadresultRef(unsafe.Pointer(__ret))
	return __v
}

// DownloadFiles function as declared in xet/xet.h:132
func DownloadFiles(files []Xetdownloadinfo, fileCount uint64, endpoint string, tokenInfo *Xettokeninfo) *Xetdownloadresult {
	cfiles, cfilesAllocMap := unpackArgSXetdownloadinfo(files)
	cfileCount, cfileCountAllocMap := (C.size_t)(fileCount), cgoAllocsUnknown
	endpoint = safeString(endpoint)
	cendpoint, cendpointAllocMap := unpackPCharString(endpoint)
	ctokenInfo, ctokenInfoAllocMap := tokenInfo.PassRef()
	__ret := C.xet_download_files(cfiles, cfileCount, cendpoint, ctokenInfo)
	runtime.KeepAlive(ctokenInfoAllocMap)
	runtime.KeepAlive(endpoint)
	runtime.KeepAlive(cendpointAllocMap)
	runtime.KeepAlive(cfileCountAllocMap)
	packSXetdownloadinfo(files, cfiles)
	runtime.KeepAlive(cfilesAllocMap)
	__v := NewXetdownloadresultRef(unsafe.Pointer(__ret))
	return __v
}

// FreeUploadResult function as declared in xet/xet.h:149
func FreeUploadResult(result *Xetuploadresult) {
	cresult, cresultAllocMap := result.PassRef()
	C.xet_free_upload_result(cresult)
	runtime.KeepAlive(cresultAllocMap)
}

// FreeDownloadResult function as declared in xet/xet.h:156
func FreeDownloadResult(result *Xetdownloadresult) {
	cresult, cresultAllocMap := result.PassRef()
	C.xet_free_download_result(cresult)
	runtime.KeepAlive(cresultAllocMap)
}
